### ISSUE TITLE
Any plans to support .NET MAUI ? 

### ISSUE THREAD

**Issue by WarBorg** [zauberzeug/quicktest#5]
hello, I really like your library and was thinking to use it in my project for some integration tests but I am migrating to MAUI as xamarin will no longer be supported, are there any plans to create a .NET MAUI branch or something along those lines to have support for .NET MAUI applications ?

**Comment by ChristopherStephan** [comment]
Hi Sergiu, migrating quicktest to MAUI is not straight forward because there is no replacement for Xamarin.Forms.Mocks planned.

https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/pull/72#issuecomment-1017663004
https://github.com/jonathanpeppers/Xamarin.Forms.Mocks/issues/76#issuecomment-1442434876

**Comment by stephanpalmer** [comment]
Hi @WarBorg, thank you for your feedback and interest in the Quicktest library! Fortunately, Xamarin.Forms.Mocks was not needed to port Quicktest to Maui. We actually already did an initial port, which you can find here:

https://github.com/zauberzeug/quicktest-maui
https://www.nuget.org/packages/Zauberzeug.QuickTest.Maui

The port has pretty much the same features as the current Xamarin.Forms.Quicktest library. We decided to create a different NuGet and Github repo as we felt this was the most clear way to distinguish between the Xamarin.Forms and MAUI versions. Also it made the git brach handling very easy.

PLEASE NOTE the following caveats/limitations:

- The port is about 10 months old. It worked well with the MAUI release from back then.
- We ported the lib to .NET 7, so it can't be used with .NET 6.
- We since did not work on Zauberzeug.QuickTest.Maui, and also did not use it, because we decided to postpone our migration to MAUI because of its desolate state.
- As with Xamarin.Forms.QuickTest, we did not get around to write good documentation. But the QuickTest API did not change in the MAUI version.

If you have any questions or problems with Zauberzeug.QuickTest.Maui, please report them on its Github.

**Comment by WarBorg** [comment]
@stephanpalmer awesome, thank you very much, our project is using .net 8.0 so I guess we should be ok, I will take a look at the new repository. Maybe as a suggestion update the readme of this repository to link other users to the MAUI version.

cheers

**Comment by stephanpalmer** [comment]
> @stephanpalmer awesome, thank you very much, our project is using .net 8.0 so I guess we should be ok, I will take a look at the new repository. Maybe as a suggestion update the readme of this repository to link other users to the MAUI version.
> 
> cheers

Thank you for the suggestion. We've updated the readme accordingly.
